### ISSUE TITLE
db.SearchTree() fails when given function for output (index out of range)

### ISSUE THREAD

**Issue by thraxil** [jmckaskill/goldap#1]
I created a little test program to run a simple query against my University's LDAP directory. I think I've figured out how to do most of what I want, but I ran into a problem with passing a function to db.SearchTree() to handle output. 

In this gist: https://gist.github.com/3239180

I run the same query, giving SearchTree() a plain struct, a slice of structs, a channel, and a function. All of them work except the function, which panics with an index out of range:

```
panic: runtime error: index out of range

goroutine 1 [running]:
reflect.(*commonType).In(0x4eebd0, 0x1, 0x130, 0xf840063000, 0x4eebd0, ...)
        /usr/local/go/src/pkg/reflect/type.go:612 +0x84
github.com/jmckaskill/goldap.(*DB).search(0xf8400000e0, 0x4eebc0, 0x4016c7, 0x58dd64, 0x7f520000001b, ...)
        /home/anders/code/go/src/github.com/jmckaskill/goldap/search.go:288 +0x8a5
github.com/jmckaskill/goldap.(*DB).SearchTree(0xf8400000e0, 0x4eebc0, 0x4016c7, 0x58dd64, 0xf80000001b, ...)
        /home/anders/code/go/src/github.com/jmckaskill/goldap/search.go:334 +0x7d
```

Line 288 of search.go is:

```
typ = ft.In(1)
```

And is called right after a 

```
if ft.NumIn() != 1 {
    panic("expected function with 1 argument")
}
```

So, it looks to me like it should be "typ = ft.In(0)" there instead. When I change that it works for me.

Of course, I'm pretty new to Go and had to reverse engineer the interface for making a query from your code since there's no real documentation. So it's entirely possible that I'm missing something obvious and did something really dumb.

**Comment by jmckaskill** [comment]
I'd say that is the fix.

From http://go.pkgdoc.org/reflect#Type:

```
// In returns the type of a function type's i'th input parameter.
// It panics if the type's Kind is not Func.
// It panics if i is not in the range [0, NumIn()).
In(i int) Type
```

The lack of documentation is unfortunately due to my constant lack of time and goldap isn't exactly the top of my priority list. I use it for querying stuff out of my active directory server at work (and works with gokerb with a bit of glue).

I'm glad it worked after that fix though. I'll push through the change.

**Comment by thraxil** [comment]
Cool. Thanks!
