### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by alextoombs** [jmckaskill/goldap#5]
I want to use [Sourcegraph](https://sourcegraph.com) for goldap code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/jmckaskill/goldap. (It should only take 30 seconds.)

Thank you!

**Comment by jmckaskill** [comment]
Done

**Comment by alextoombs** [comment]
Thanks, appreciate it!
